name: Github Action Flow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Listing files 1
        run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
            echo "${{ github.token }}"
            git clone git@github:$GITHUB_REPOSITORY
            git checkout $GITHUB_SHA
      - name: Checkout file
        uses: actions/checkout@v1
      - name: Listing files 2
        run: |
            pwd
            ls
      - name: Simple Javascript Action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Quan
      - name: Log the time
        run: echo ${{ steps.simple-action.outputs.time }}
          